import { createFileRoute, Link } from '@tanstack/react-router'
import { useLiveQuery } from '@tanstack/react-db'
import { Button } from '@/components/ui/button'
import { useState } from 'react'
import { Users } from 'lucide-react'
import { useCollections } from '../__root'
import { eq } from '@tanstack/react-db'

export const Route = createFileRoute('/companies/')({
  component: CompaniesPage,
  ssr: false,
})

function CompanyVisitorCount({ companyId }: { companyId: string }) {
  // For visitor count, we would create a separate collection or use TanStack Query directly
  // since it's a computed/analytics value. For now, showing placeholder.
  return (
    <div className="flex items-center gap-2 text-sm text-muted-foreground">
      <Users className="h-4 w-4" />
      <span>-- visitors (24h)</span>
    </div>
  )
}

function CompaniesPage() {
  const { companiesCollection } = useCollections()

  // Use useLiveQuery to reactively query the companies collection
  const { data: companies } = useLiveQuery((q) =>
    q.from({ company: companiesCollection }),
  )

  const [isCreating, setIsCreating] = useState(false)
  const [name, setName] = useState('')
  const [domain, setDomain] = useState('')

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!name || !domain) return

    try {
      // Optimistic mutation - updates UI immediately
      companiesCollection.insert({
        id: crypto.randomUUID(),
        name,
        domain,
        apiKey: '', // Will be generated by backend
        createdAt: new Date(),
        updatedAt: new Date(),
      })

      setName('')
      setDomain('')
      setIsCreating(false)
    } catch (error) {
      console.error('Error creating company:', error)
    }
  }

  return (
    <div className="container mx-auto p-8">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold">Companies</h1>
          <p className="text-muted-foreground mt-2">
            Manage your attribution tracking companies
          </p>
        </div>
        <Button onClick={() => setIsCreating(true)}>Create Company</Button>
      </div>

      {isCreating && (
        <div className="mb-8 p-6 border rounded-lg bg-card">
          <h2 className="text-xl font-semibold mb-4">Create New Company</h2>
          <form onSubmit={handleCreate} className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">
                Company Name
              </label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full px-3 py-2 border rounded-md bg-background text-foreground"
                placeholder="My Marketing Campaign"
                required
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-2">Domain</label>
              <input
                type="text"
                value={domain}
                onChange={(e) => setDomain(e.target.value)}
                className="w-full px-3 py-2 border rounded-md bg-background text-foreground"
                placeholder="example.com"
                required
              />
            </div>
            <div className="flex gap-2">
              <Button type="submit">Create</Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => setIsCreating(false)}
              >
                Cancel
              </Button>
            </div>
          </form>
        </div>
      )}

      {!companies ? (
        <div>Loading companies...</div>
      ) : companies.length === 0 ? (
        <div className="text-center py-12 border rounded-lg bg-card">
          <p className="text-muted-foreground mb-4">
            No companies yet. Create your first company to start tracking
            attribution.
          </p>
          <Button onClick={() => setIsCreating(true)}>Create Company</Button>
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {companies.map((company) => (
            <Link
              key={company.id}
              to="/companies/$companyId"
              params={{ companyId: company.id }}
              className="block"
            >
              <div className="p-6 border rounded-lg bg-card text-card-foreground hover:border-primary transition-colors cursor-pointer">
                <h3 className="text-xl font-semibold mb-2">{company.name}</h3>
                <p className="text-sm text-muted-foreground mb-2">
                  {company.domain}
                </p>
                <div className="mb-4">
                  <CompanyVisitorCount companyId={company.id} />
                </div>
                <div className="text-xs font-mono bg-muted p-2 rounded overflow-x-auto">
                  {company.apiKey || 'Generating...'}
                </div>
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
