/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesCompanyIdRouteRouteImport } from './routes/companies/$companyId/route'
import { Route as CompaniesCompanyIdIndexRouteImport } from './routes/companies/$companyId/index'
import { Route as CompaniesCompanyIdVisitorsIndexRouteImport } from './routes/companies/$companyId/visitors/index'
import { Route as CompaniesCompanyIdTrackingIndexRouteImport } from './routes/companies/$companyId/tracking/index'
import { Route as CompaniesCompanyIdSettingsIndexRouteImport } from './routes/companies/$companyId/settings/index'
import { Route as CompaniesCompanyIdRoiIndexRouteImport } from './routes/companies/$companyId/roi/index'
import { Route as CompaniesCompanyIdPatientsIndexRouteImport } from './routes/companies/$companyId/patients/index'
import { Route as CompaniesCompanyIdKpisIndexRouteImport } from './routes/companies/$companyId/kpis/index'
import { Route as CompaniesCompanyIdContactsIndexRouteImport } from './routes/companies/$companyId/contacts/index'
import { Route as CompaniesCompanyIdCmsPagesIndexRouteImport } from './routes/companies/$companyId/cms-pages/index'
import { Route as CompaniesCompanyIdAppointmentsIndexRouteImport } from './routes/companies/$companyId/appointments/index'
import { Route as CompaniesCompanyIdPatientsPatientIdRouteImport } from './routes/companies/$companyId/patients/$patientId'
import { Route as CompaniesCompanyIdCmsPagesCreateRouteImport } from './routes/companies/$companyId/cms-pages/create'
import { Route as CompaniesCompanyIdCmsPagesPageIdRouteImport } from './routes/companies/$companyId/cms-pages/$pageId'
import { Route as CompaniesCompanyIdContactsContactIdIndexRouteImport } from './routes/companies/$companyId/contacts/$contactId/index'
import { Route as CompaniesCompanyIdKpisServicesServiceIdRouteImport } from './routes/companies/$companyId/kpis/services/$serviceId'

const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesCompanyIdRouteRoute = CompaniesCompanyIdRouteRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesCompanyIdIndexRoute = CompaniesCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesCompanyIdRouteRoute,
} as any)
const CompaniesCompanyIdVisitorsIndexRoute =
  CompaniesCompanyIdVisitorsIndexRouteImport.update({
    id: '/visitors/',
    path: '/visitors/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdTrackingIndexRoute =
  CompaniesCompanyIdTrackingIndexRouteImport.update({
    id: '/tracking/',
    path: '/tracking/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdSettingsIndexRoute =
  CompaniesCompanyIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdRoiIndexRoute =
  CompaniesCompanyIdRoiIndexRouteImport.update({
    id: '/roi/',
    path: '/roi/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdPatientsIndexRoute =
  CompaniesCompanyIdPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdKpisIndexRoute =
  CompaniesCompanyIdKpisIndexRouteImport.update({
    id: '/kpis/',
    path: '/kpis/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdContactsIndexRoute =
  CompaniesCompanyIdContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdCmsPagesIndexRoute =
  CompaniesCompanyIdCmsPagesIndexRouteImport.update({
    id: '/cms-pages/',
    path: '/cms-pages/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdAppointmentsIndexRoute =
  CompaniesCompanyIdAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdPatientsPatientIdRoute =
  CompaniesCompanyIdPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdCmsPagesCreateRoute =
  CompaniesCompanyIdCmsPagesCreateRouteImport.update({
    id: '/cms-pages/create',
    path: '/cms-pages/create',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdCmsPagesPageIdRoute =
  CompaniesCompanyIdCmsPagesPageIdRouteImport.update({
    id: '/cms-pages/$pageId',
    path: '/cms-pages/$pageId',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdContactsContactIdIndexRoute =
  CompaniesCompanyIdContactsContactIdIndexRouteImport.update({
    id: '/contacts/$contactId/',
    path: '/contacts/$contactId/',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)
const CompaniesCompanyIdKpisServicesServiceIdRoute =
  CompaniesCompanyIdKpisServicesServiceIdRouteImport.update({
    id: '/kpis/services/$serviceId',
    path: '/kpis/services/$serviceId',
    getParentRoute: () => CompaniesCompanyIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/companies/$companyId': typeof CompaniesCompanyIdRouteRouteWithChildren
  '/companies/': typeof CompaniesIndexRoute
  '/companies/$companyId/': typeof CompaniesCompanyIdIndexRoute
  '/companies/$companyId/cms-pages/$pageId': typeof CompaniesCompanyIdCmsPagesPageIdRoute
  '/companies/$companyId/cms-pages/create': typeof CompaniesCompanyIdCmsPagesCreateRoute
  '/companies/$companyId/patients/$patientId': typeof CompaniesCompanyIdPatientsPatientIdRoute
  '/companies/$companyId/appointments': typeof CompaniesCompanyIdAppointmentsIndexRoute
  '/companies/$companyId/cms-pages': typeof CompaniesCompanyIdCmsPagesIndexRoute
  '/companies/$companyId/contacts': typeof CompaniesCompanyIdContactsIndexRoute
  '/companies/$companyId/kpis': typeof CompaniesCompanyIdKpisIndexRoute
  '/companies/$companyId/patients': typeof CompaniesCompanyIdPatientsIndexRoute
  '/companies/$companyId/roi': typeof CompaniesCompanyIdRoiIndexRoute
  '/companies/$companyId/settings': typeof CompaniesCompanyIdSettingsIndexRoute
  '/companies/$companyId/tracking': typeof CompaniesCompanyIdTrackingIndexRoute
  '/companies/$companyId/visitors': typeof CompaniesCompanyIdVisitorsIndexRoute
  '/companies/$companyId/kpis/services/$serviceId': typeof CompaniesCompanyIdKpisServicesServiceIdRoute
  '/companies/$companyId/contacts/$contactId': typeof CompaniesCompanyIdContactsContactIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdIndexRoute
  '/companies/$companyId/cms-pages/$pageId': typeof CompaniesCompanyIdCmsPagesPageIdRoute
  '/companies/$companyId/cms-pages/create': typeof CompaniesCompanyIdCmsPagesCreateRoute
  '/companies/$companyId/patients/$patientId': typeof CompaniesCompanyIdPatientsPatientIdRoute
  '/companies/$companyId/appointments': typeof CompaniesCompanyIdAppointmentsIndexRoute
  '/companies/$companyId/cms-pages': typeof CompaniesCompanyIdCmsPagesIndexRoute
  '/companies/$companyId/contacts': typeof CompaniesCompanyIdContactsIndexRoute
  '/companies/$companyId/kpis': typeof CompaniesCompanyIdKpisIndexRoute
  '/companies/$companyId/patients': typeof CompaniesCompanyIdPatientsIndexRoute
  '/companies/$companyId/roi': typeof CompaniesCompanyIdRoiIndexRoute
  '/companies/$companyId/settings': typeof CompaniesCompanyIdSettingsIndexRoute
  '/companies/$companyId/tracking': typeof CompaniesCompanyIdTrackingIndexRoute
  '/companies/$companyId/visitors': typeof CompaniesCompanyIdVisitorsIndexRoute
  '/companies/$companyId/kpis/services/$serviceId': typeof CompaniesCompanyIdKpisServicesServiceIdRoute
  '/companies/$companyId/contacts/$contactId': typeof CompaniesCompanyIdContactsContactIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/companies/$companyId': typeof CompaniesCompanyIdRouteRouteWithChildren
  '/companies/': typeof CompaniesIndexRoute
  '/companies/$companyId/': typeof CompaniesCompanyIdIndexRoute
  '/companies/$companyId/cms-pages/$pageId': typeof CompaniesCompanyIdCmsPagesPageIdRoute
  '/companies/$companyId/cms-pages/create': typeof CompaniesCompanyIdCmsPagesCreateRoute
  '/companies/$companyId/patients/$patientId': typeof CompaniesCompanyIdPatientsPatientIdRoute
  '/companies/$companyId/appointments/': typeof CompaniesCompanyIdAppointmentsIndexRoute
  '/companies/$companyId/cms-pages/': typeof CompaniesCompanyIdCmsPagesIndexRoute
  '/companies/$companyId/contacts/': typeof CompaniesCompanyIdContactsIndexRoute
  '/companies/$companyId/kpis/': typeof CompaniesCompanyIdKpisIndexRoute
  '/companies/$companyId/patients/': typeof CompaniesCompanyIdPatientsIndexRoute
  '/companies/$companyId/roi/': typeof CompaniesCompanyIdRoiIndexRoute
  '/companies/$companyId/settings/': typeof CompaniesCompanyIdSettingsIndexRoute
  '/companies/$companyId/tracking/': typeof CompaniesCompanyIdTrackingIndexRoute
  '/companies/$companyId/visitors/': typeof CompaniesCompanyIdVisitorsIndexRoute
  '/companies/$companyId/kpis/services/$serviceId': typeof CompaniesCompanyIdKpisServicesServiceIdRoute
  '/companies/$companyId/contacts/$contactId/': typeof CompaniesCompanyIdContactsContactIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/companies/$companyId'
    | '/companies/'
    | '/companies/$companyId/'
    | '/companies/$companyId/cms-pages/$pageId'
    | '/companies/$companyId/cms-pages/create'
    | '/companies/$companyId/patients/$patientId'
    | '/companies/$companyId/appointments'
    | '/companies/$companyId/cms-pages'
    | '/companies/$companyId/contacts'
    | '/companies/$companyId/kpis'
    | '/companies/$companyId/patients'
    | '/companies/$companyId/roi'
    | '/companies/$companyId/settings'
    | '/companies/$companyId/tracking'
    | '/companies/$companyId/visitors'
    | '/companies/$companyId/kpis/services/$serviceId'
    | '/companies/$companyId/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/companies/$companyId'
    | '/companies/$companyId/cms-pages/$pageId'
    | '/companies/$companyId/cms-pages/create'
    | '/companies/$companyId/patients/$patientId'
    | '/companies/$companyId/appointments'
    | '/companies/$companyId/cms-pages'
    | '/companies/$companyId/contacts'
    | '/companies/$companyId/kpis'
    | '/companies/$companyId/patients'
    | '/companies/$companyId/roi'
    | '/companies/$companyId/settings'
    | '/companies/$companyId/tracking'
    | '/companies/$companyId/visitors'
    | '/companies/$companyId/kpis/services/$serviceId'
    | '/companies/$companyId/contacts/$contactId'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/companies/$companyId'
    | '/companies/'
    | '/companies/$companyId/'
    | '/companies/$companyId/cms-pages/$pageId'
    | '/companies/$companyId/cms-pages/create'
    | '/companies/$companyId/patients/$patientId'
    | '/companies/$companyId/appointments/'
    | '/companies/$companyId/cms-pages/'
    | '/companies/$companyId/contacts/'
    | '/companies/$companyId/kpis/'
    | '/companies/$companyId/patients/'
    | '/companies/$companyId/roi/'
    | '/companies/$companyId/settings/'
    | '/companies/$companyId/tracking/'
    | '/companies/$companyId/visitors/'
    | '/companies/$companyId/kpis/services/$serviceId'
    | '/companies/$companyId/contacts/$contactId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$companyId/': {
      id: '/companies/$companyId/'
      path: '/'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof CompaniesCompanyIdIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/visitors/': {
      id: '/companies/$companyId/visitors/'
      path: '/visitors'
      fullPath: '/companies/$companyId/visitors'
      preLoaderRoute: typeof CompaniesCompanyIdVisitorsIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/tracking/': {
      id: '/companies/$companyId/tracking/'
      path: '/tracking'
      fullPath: '/companies/$companyId/tracking'
      preLoaderRoute: typeof CompaniesCompanyIdTrackingIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/settings/': {
      id: '/companies/$companyId/settings/'
      path: '/settings'
      fullPath: '/companies/$companyId/settings'
      preLoaderRoute: typeof CompaniesCompanyIdSettingsIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/roi/': {
      id: '/companies/$companyId/roi/'
      path: '/roi'
      fullPath: '/companies/$companyId/roi'
      preLoaderRoute: typeof CompaniesCompanyIdRoiIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/patients/': {
      id: '/companies/$companyId/patients/'
      path: '/patients'
      fullPath: '/companies/$companyId/patients'
      preLoaderRoute: typeof CompaniesCompanyIdPatientsIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/kpis/': {
      id: '/companies/$companyId/kpis/'
      path: '/kpis'
      fullPath: '/companies/$companyId/kpis'
      preLoaderRoute: typeof CompaniesCompanyIdKpisIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/contacts/': {
      id: '/companies/$companyId/contacts/'
      path: '/contacts'
      fullPath: '/companies/$companyId/contacts'
      preLoaderRoute: typeof CompaniesCompanyIdContactsIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/cms-pages/': {
      id: '/companies/$companyId/cms-pages/'
      path: '/cms-pages'
      fullPath: '/companies/$companyId/cms-pages'
      preLoaderRoute: typeof CompaniesCompanyIdCmsPagesIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/appointments/': {
      id: '/companies/$companyId/appointments/'
      path: '/appointments'
      fullPath: '/companies/$companyId/appointments'
      preLoaderRoute: typeof CompaniesCompanyIdAppointmentsIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/patients/$patientId': {
      id: '/companies/$companyId/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/companies/$companyId/patients/$patientId'
      preLoaderRoute: typeof CompaniesCompanyIdPatientsPatientIdRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/cms-pages/create': {
      id: '/companies/$companyId/cms-pages/create'
      path: '/cms-pages/create'
      fullPath: '/companies/$companyId/cms-pages/create'
      preLoaderRoute: typeof CompaniesCompanyIdCmsPagesCreateRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/cms-pages/$pageId': {
      id: '/companies/$companyId/cms-pages/$pageId'
      path: '/cms-pages/$pageId'
      fullPath: '/companies/$companyId/cms-pages/$pageId'
      preLoaderRoute: typeof CompaniesCompanyIdCmsPagesPageIdRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/contacts/$contactId/': {
      id: '/companies/$companyId/contacts/$contactId/'
      path: '/contacts/$contactId'
      fullPath: '/companies/$companyId/contacts/$contactId'
      preLoaderRoute: typeof CompaniesCompanyIdContactsContactIdIndexRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
    '/companies/$companyId/kpis/services/$serviceId': {
      id: '/companies/$companyId/kpis/services/$serviceId'
      path: '/kpis/services/$serviceId'
      fullPath: '/companies/$companyId/kpis/services/$serviceId'
      preLoaderRoute: typeof CompaniesCompanyIdKpisServicesServiceIdRouteImport
      parentRoute: typeof CompaniesCompanyIdRouteRoute
    }
  }
}

interface CompaniesCompanyIdRouteRouteChildren {
  CompaniesCompanyIdIndexRoute: typeof CompaniesCompanyIdIndexRoute
  CompaniesCompanyIdCmsPagesPageIdRoute: typeof CompaniesCompanyIdCmsPagesPageIdRoute
  CompaniesCompanyIdCmsPagesCreateRoute: typeof CompaniesCompanyIdCmsPagesCreateRoute
  CompaniesCompanyIdPatientsPatientIdRoute: typeof CompaniesCompanyIdPatientsPatientIdRoute
  CompaniesCompanyIdAppointmentsIndexRoute: typeof CompaniesCompanyIdAppointmentsIndexRoute
  CompaniesCompanyIdCmsPagesIndexRoute: typeof CompaniesCompanyIdCmsPagesIndexRoute
  CompaniesCompanyIdContactsIndexRoute: typeof CompaniesCompanyIdContactsIndexRoute
  CompaniesCompanyIdKpisIndexRoute: typeof CompaniesCompanyIdKpisIndexRoute
  CompaniesCompanyIdPatientsIndexRoute: typeof CompaniesCompanyIdPatientsIndexRoute
  CompaniesCompanyIdRoiIndexRoute: typeof CompaniesCompanyIdRoiIndexRoute
  CompaniesCompanyIdSettingsIndexRoute: typeof CompaniesCompanyIdSettingsIndexRoute
  CompaniesCompanyIdTrackingIndexRoute: typeof CompaniesCompanyIdTrackingIndexRoute
  CompaniesCompanyIdVisitorsIndexRoute: typeof CompaniesCompanyIdVisitorsIndexRoute
  CompaniesCompanyIdKpisServicesServiceIdRoute: typeof CompaniesCompanyIdKpisServicesServiceIdRoute
  CompaniesCompanyIdContactsContactIdIndexRoute: typeof CompaniesCompanyIdContactsContactIdIndexRoute
}

const CompaniesCompanyIdRouteRouteChildren: CompaniesCompanyIdRouteRouteChildren =
  {
    CompaniesCompanyIdIndexRoute: CompaniesCompanyIdIndexRoute,
    CompaniesCompanyIdCmsPagesPageIdRoute:
      CompaniesCompanyIdCmsPagesPageIdRoute,
    CompaniesCompanyIdCmsPagesCreateRoute:
      CompaniesCompanyIdCmsPagesCreateRoute,
    CompaniesCompanyIdPatientsPatientIdRoute:
      CompaniesCompanyIdPatientsPatientIdRoute,
    CompaniesCompanyIdAppointmentsIndexRoute:
      CompaniesCompanyIdAppointmentsIndexRoute,
    CompaniesCompanyIdCmsPagesIndexRoute: CompaniesCompanyIdCmsPagesIndexRoute,
    CompaniesCompanyIdContactsIndexRoute: CompaniesCompanyIdContactsIndexRoute,
    CompaniesCompanyIdKpisIndexRoute: CompaniesCompanyIdKpisIndexRoute,
    CompaniesCompanyIdPatientsIndexRoute: CompaniesCompanyIdPatientsIndexRoute,
    CompaniesCompanyIdRoiIndexRoute: CompaniesCompanyIdRoiIndexRoute,
    CompaniesCompanyIdSettingsIndexRoute: CompaniesCompanyIdSettingsIndexRoute,
    CompaniesCompanyIdTrackingIndexRoute: CompaniesCompanyIdTrackingIndexRoute,
    CompaniesCompanyIdVisitorsIndexRoute: CompaniesCompanyIdVisitorsIndexRoute,
    CompaniesCompanyIdKpisServicesServiceIdRoute:
      CompaniesCompanyIdKpisServicesServiceIdRoute,
    CompaniesCompanyIdContactsContactIdIndexRoute:
      CompaniesCompanyIdContactsContactIdIndexRoute,
  }

const CompaniesCompanyIdRouteRouteWithChildren =
  CompaniesCompanyIdRouteRoute._addFileChildren(
    CompaniesCompanyIdRouteRouteChildren,
  )

interface CompaniesRouteChildren {
  CompaniesCompanyIdRouteRoute: typeof CompaniesCompanyIdRouteRouteWithChildren
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRouteRoute: CompaniesCompanyIdRouteRouteWithChildren,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
